version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/aratasomj:cached
      - fedeps:/workspaces/aratasomj/frontend/node_modules:delegated
      - bedeps:/workspaces/aratasomj/backend/.venv:delegated
    working_dir: /workspaces/aratasomj
    command: sleep infinity

volumes:
  fedeps:
  bedeps:
